/** Generated by scripts/gen_attribute_types.py — do not edit. */

export const ATTRIBUTE_TYPES = [
  "string",
  "text",
  "integer",
  "decimal",
  "number",
  "boolean",
  "date",
  "timestamp",
  "time",
  "json",
  "dictionary",
  "reference",
] as const;

export type AttributeType = (typeof ATTRIBUTE_TYPES)[number];

export const ATTRIBUTE_TYPE_CATALOG = {
  string: {
    config: {
      max_length: { kind: "int", minimum: 1, maximum: 65535, atMost: null },
    },
    physical: { template: "VARCHAR({max_length})", bare: "VARCHAR" },
  },
  text: {
    config: {},
    physical: { template: "TEXT", bare: "TEXT" },
  },
  integer: {
    config: {},
    physical: { template: "BIGINT", bare: "BIGINT" },
  },
  decimal: {
    config: {
      precision: { kind: "int", minimum: 1, maximum: 1000, atMost: null },
      scale: { kind: "int", minimum: 0, maximum: 1000, atMost: "precision" },
    },
    physical: { template: "NUMERIC({precision},{scale})", bare: "NUMERIC" },
  },
  number: {
    config: {},
    physical: { template: "DOUBLE PRECISION", bare: "DOUBLE PRECISION" },
  },
  boolean: {
    config: {},
    physical: { template: "BOOLEAN", bare: "BOOLEAN" },
  },
  date: {
    config: {},
    physical: { template: "DATE", bare: "DATE" },
  },
  timestamp: {
    config: {},
    physical: { template: "TIMESTAMPTZ", bare: "TIMESTAMPTZ" },
  },
  time: {
    config: {},
    physical: { template: "TIME", bare: "TIME" },
  },
  json: {
    config: {},
    physical: { template: "JSONB", bare: "JSONB" },
  },
  dictionary: {
    config: {
      dictionary_id: { kind: "string" },
    },
    physical: { template: "VARCHAR(64)", bare: "VARCHAR(64)" },
  },
  reference: {
    config: {
      target_entity_id: { kind: "string" },
    },
    physical: { template: "VARCHAR | BIGINT", bare: "VARCHAR | BIGINT" },
  },
} as const satisfies Record<
  AttributeType,
  {
    config: Record<
      string,
      | {
          kind: "int";
          minimum: number;
          maximum: number;
          atMost: string | null;
        }
      | { kind: "string" }
    >;
    physical: { template: string; bare: string };
  }
>;
