"""Entity publish create and drop Job tests against a recording DDL port."""

from __future__ import annotations

import os
from dataclasses import replace

import pytest
from fastapi.testclient import TestClient

os.environ["REFRAQ_STORE_BACKEND"] = "memory"
os.environ["REFRAQ_SECRETS_MASTER_KEY"] = "test-secrets-master-key"
os.environ["CELERY_TASK_ALWAYS_EAGER"] = "1"
os.environ.pop("DATABASE_URL", None)
os.environ.pop("REDIS_URL", None)
os.environ.setdefault("CELERY_BROKER_URL", "memory://")

from backend.admin.audit_store import get_audit_store  # noqa: E402
from backend.admin.roles import seed_roles  # noqa: E402
from backend.admin.role_store import get_role_store  # noqa: E402
from backend.admin.security import hash_password  # noqa: E402
from backend.admin.user_store import get_user_store  # noqa: E402
from backend.core.time import utc_now  # noqa: E402
from backend.entity.jobs import find_inflight_entity_table_job  # noqa: E402
from backend.entity.kinds import KIND_RECONCILE  # noqa: E402
from backend.entity.lifecycle import PUBLISHING  # noqa: E402
from backend.entity.locks import try_acquire_entity_table_lock  # noqa: E402
from backend.entity.store import get_entity_store  # noqa: E402
from backend.entity.table_port import (  # noqa: E402
    EntityTableHasRows,
    RecordingEntityTablePort,
    bind_entity_table_port,
    get_entity_table_port,
    reset_entity_table_port,
)
from backend.jobs.store import create_queued_job, get_job_store  # noqa: E402
from backend.main import app  # noqa: E402
from backend.tests.test_entity import SKU, _create_body  # noqa: E402


@pytest.fixture()
def port() -> RecordingEntityTablePort:
    recording = RecordingEntityTablePort()
    bind_entity_table_port(recording)
    return recording


@pytest.fixture()
def client(port: RecordingEntityTablePort) -> TestClient:
    del port
    roles = get_role_store()
    seed_roles(roles)
    admin = roles.get_by_key("super_admin")
    assert admin is not None
    get_user_store().create_user(
        account="admin",
        display_name="Admin",
        password_hash=hash_password("secret"),
        role_id=admin.id,
        status="active",
    )
    with TestClient(app) as test_client:
        login = test_client.post(
            "/auth/login", json={"account": "admin", "password": "secret"}
        )
        assert login.status_code == 200, login.text
        yield test_client


def _create(client: TestClient) -> dict:
    created = client.post("/entities", json=_create_body())
    assert created.status_code == 201, created.text
    return created.json()["entity"]


def _publish(client: TestClient, entity: dict) -> dict:
    version_id = entity["current_version"]["id"]
    published = client.post(
        f"/entities/{entity['id']}/versions/{version_id}/publish"
    )
    assert published.status_code == 201, published.text
    return published.json()


def test_publish_creates_table_and_locks(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    published = _publish(client, entity)
    job = published["job"]
    assert job["kind"] == "entity_reconcile"
    assert job["status"] == "succeeded"
    assert job["result"]["schema"] == "entity_reconcile.v1"
    assert job["result"]["action"] == "created"
    assert job["result"]["columns_added"] == 1
    assert job["result"]["unique_added"] == 1
    create_sql = port.statements[0]
    assert "CREATE TABLE" in create_sql
    assert '"public"."material"' in create_sql
    assert '"row_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' in create_sql
    assert "UNIQUE" in create_sql

    detail = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    version = detail.json()["version"]
    assert version["publish_status"] == "published"
    assert version["table_name"] == "material"
    alignment = version["alignment"]
    assert alignment["table_present"] is True
    assert alignment["definition_ahead"] is False
    assert alignment["latest_job_id"] == job["id"]
    assert alignment["latest_job_status"] == "succeeded"

    events, _ = get_audit_store().list_events(action="entity.publish_enqueue")
    assert events

    second = client.post(f"/entities/{entity['id']}/versions/{version_id}/publish")
    assert second.status_code == 422
    assert second.json()["code"] == "ENTITY_NOT_UNPUBLISHED"


def test_publish_successor_renames_live_table(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    entity = _create(client)
    v1 = entity["current_version"]["id"]
    _publish(client, entity)
    opened = client.post(f"/entities/{entity['id']}/versions", json={})
    assert opened.status_code == 201
    v2 = opened.json()["version"]["id"]
    live = client.get(f"/entities/{entity['id']}/versions/{v1}")
    assert live.json()["version"]["table_name"] == "material"
    current = client.get(f"/entities/{entity['id']}").json()["entity"]
    _publish(client, current)
    renamed = client.get(f"/entities/{entity['id']}/versions/{v1}")
    assert renamed.json()["version"]["table_name"] == "material__rfq_v1"
    successor = client.get(f"/entities/{entity['id']}/versions/{v2}")
    assert successor.json()["version"]["table_name"] == "material"
    assert any("RENAME TO" in stmt for stmt in port.statements)
    assert any('"public"."material__rfq_v1"' in stmt for stmt in port.statements)

    dropped = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert dropped.status_code == 201, dropped.text
    job = get_job_store().get(dropped.json()["job"]["id"])
    assert job is not None
    assert job.status == "succeeded"


def test_publish_name_conflict_rolls_back(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    port.publish_table(
        "public", "material", [], archive_as=None, archive_attributes=None
    )
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    published = client.post(
        f"/entities/{entity['id']}/versions/{version_id}/publish"
    )
    assert published.status_code == 201
    job = get_job_store().get(published.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "ENTITY_TABLE_NAME_CONFLICT"
    version = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    assert version.json()["version"]["publish_status"] == "unpublished"
    assert version.json()["version"]["alignment"]["table_present"] is False


def test_revert_failure_is_logged_and_original_error_kept(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    class _RevertFails(RecordingEntityTablePort):
        def revert_publish_table(
            self,
            schema: str,
            stem: str,
            *,
            archive_as: str | None,
            archive_attributes: list | None,
        ) -> None:
            del schema, stem, archive_as, archive_attributes
            raise RuntimeError("archive restore failed")

    bind_entity_table_port(_RevertFails())

    def _snapshot_fails(attributes: list) -> list:
        del attributes
        raise RuntimeError("snapshot write failed")

    monkeypatch.setattr(
        "backend.entity.align.snapshot_from_attributes", _snapshot_fails
    )
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    published = client.post(
        f"/entities/{entity['id']}/versions/{version_id}/publish"
    )
    assert published.status_code == 201, published.text
    job = get_job_store().get(published.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "JOB_EXECUTION_FAILED"
    assert "snapshot write failed" in (job.error_summary or "")
    assert "revert failed: archive restore failed" in job.log_body


def test_save_refused_after_publish(client: TestClient) -> None:
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    _publish(client, entity)
    refused = client.patch(
        f"/entities/{entity['id']}/versions/{version_id}",
        json={"attributes": [SKU, {**SKU, "name": "note", "nullable": True}]},
    )
    assert refused.status_code == 422
    assert refused.json()["code"] == "ENTITY_NOT_UNPUBLISHED"


def test_inflight_publish_is_returned_not_duplicated(client: TestClient) -> None:
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    queued = create_queued_job(
        kind=KIND_RECONCILE,
        input={"entity_version_id": version_id},
        created_by="user_admin",
        trigger_kind="user",
        trigger_ref="user_admin",
    )
    store = get_entity_store()
    version = store.get_version(version_id)
    assert version is not None
    store.save_version(
        replace(
            version,
            publish_status=PUBLISHING,
            latest_reconcile_job_id=queued.id,
            updated_at=utc_now(),
        )
    )
    again = client.post(f"/entities/{entity['id']}/versions/{version_id}/publish")
    assert again.status_code == 200
    assert again.json()["job"]["id"] == queued.id
    records, _ = get_job_store().list(kind=KIND_RECONCILE)
    assert len(records) == 1


def test_drop_current_refused_until_deprecated(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    entity = _create(client)
    v1 = entity["current_version"]["id"]
    _publish(client, entity)
    current_drop = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert current_drop.status_code == 422
    assert current_drop.json()["code"] == "ENTITY_VERSION_NOT_SUPERSEDED"

    opened = client.post(f"/entities/{entity['id']}/versions", json={})
    assert opened.status_code == 201
    present_delete = client.delete(f"/entities/{entity['id']}")
    assert present_delete.status_code == 409
    assert present_delete.json()["code"] == "ENTITY_ALREADY_PUBLISHED"

    still_live = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert still_live.status_code == 422
    assert still_live.json()["code"] == "ENTITY_VERSION_NOT_SUPERSEDED"

    assert client.post(f"/entities/{entity['id']}/deprecate").status_code == 200
    dropped = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert dropped.status_code == 201, dropped.text
    job = get_job_store().get(dropped.json()["job"]["id"])
    assert job is not None
    assert job.status == "succeeded"
    assert job.result["schema"] == "entity_table_drop.v1"
    assert any("DROP TABLE" in stmt for stmt in port.statements)

    already = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert already.status_code == 200
    assert already.json()["job"] is None


def test_drop_current_after_deprecate(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    entity = _create(client)
    v1 = entity["current_version"]["id"]
    _publish(client, entity)
    assert client.post(f"/entities/{entity['id']}/deprecate").status_code == 200
    dropped = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert dropped.status_code == 201, dropped.text
    job = get_job_store().get(dropped.json()["job"]["id"])
    assert job is not None
    assert job.status == "succeeded"


def test_drop_non_empty_table_fails_job(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    class _NonEmpty(RecordingEntityTablePort):
        def drop_table(self, schema: str, table: str) -> None:
            if table == "material__rfq_v1":
                raise EntityTableHasRows()
            super().drop_table(schema, table)

    occupied = _NonEmpty()
    occupied.statements = port.statements
    occupied._tables = port._tables
    bind_entity_table_port(occupied)
    entity = _create(client)
    v1 = entity["current_version"]["id"]
    _publish(client, entity)
    assert client.post(f"/entities/{entity['id']}/versions", json={}).status_code == 201
    current = client.get(f"/entities/{entity['id']}").json()["entity"]
    _publish(client, current)
    dropped = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert dropped.status_code == 201
    job = get_job_store().get(dropped.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "ENTITY_TABLE_NOT_EMPTY"
    version = client.get(f"/entities/{entity['id']}/versions/{v1}")
    assert version.json()["version"]["alignment"]["table_present"] is True


def test_publish_and_drop_share_lock(client: TestClient) -> None:
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    held = try_acquire_entity_table_lock(entity["id"])
    assert held is not None
    try:
        published = client.post(
            f"/entities/{entity['id']}/versions/{version_id}/publish"
        )
        assert published.status_code == 201
        job = get_job_store().get(published.json()["job"]["id"])
        assert job is not None
        assert job.status == "failed"
        assert job.error_code == "JOB_ALREADY_ACTIVE"
        version = client.get(f"/entities/{entity['id']}/versions/{version_id}")
        assert version.json()["version"]["publish_status"] == "unpublished"
    finally:
        held.release()
    assert find_inflight_entity_table_job(version_id) is None


class _PersistentNoEntityUrl:
    store_backend = "persistent"
    entity_database_url = None


def test_memory_without_bind_uses_recording() -> None:
    reset_entity_table_port()
    port = get_entity_table_port()
    assert isinstance(port, RecordingEntityTablePort)


def test_explicit_bind_wins_when_persistent_has_no_entity_url(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    recording = RecordingEntityTablePort()
    bind_entity_table_port(recording)
    monkeypatch.setattr(
        "backend.entity.table_port.get_settings", lambda: _PersistentNoEntityUrl()
    )
    assert get_entity_table_port() is recording


def test_persistent_without_entity_url_does_not_use_recording(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    reset_entity_table_port()
    monkeypatch.setattr(
        "backend.entity.table_port.get_settings", lambda: _PersistentNoEntityUrl()
    )
    with pytest.raises(ValueError, match="ENTITY_DATABASE_URL"):
        get_entity_table_port()


def test_persistent_publish_without_entity_url_fails_and_rolls_back(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    reset_entity_table_port()
    monkeypatch.setattr(
        "backend.entity.table_port.get_settings", lambda: _PersistentNoEntityUrl()
    )
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    published = client.post(
        f"/entities/{entity['id']}/versions/{version_id}/publish"
    )
    assert published.status_code == 201, published.text
    job = get_job_store().get(published.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "JOB_EXECUTION_FAILED"
    assert "ENTITY_DATABASE_URL" in (job.error_summary or "")
    version = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    assert version.json()["version"]["publish_status"] == "unpublished"
    alignment = version.json()["version"]["alignment"]
    assert alignment["table_present"] is False
    assert alignment["latest_job_status"] == "failed"


def test_persistent_drop_without_entity_url_fails_and_keeps_snapshot(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    entity = _create(client)
    v1 = entity["current_version"]["id"]
    store = get_entity_store()
    version = store.get_version(v1)
    assert version is not None
    store.save_version(
        replace(
            version,
            publish_status="published",
            materialized_attributes=[
                {"name": "sku", "normalized_type": "string", "nullable": False}
            ],
            updated_at=utc_now(),
        )
    )
    assert client.post(f"/entities/{entity['id']}/deprecate").status_code == 200
    reset_entity_table_port()
    monkeypatch.setattr(
        "backend.entity.table_port.get_settings", lambda: _PersistentNoEntityUrl()
    )
    dropped = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert dropped.status_code == 201, dropped.text
    job = get_job_store().get(dropped.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "JOB_EXECUTION_FAILED"
    assert "ENTITY_DATABASE_URL" in (job.error_summary or "")
    kept = client.get(f"/entities/{entity['id']}/versions/{v1}")
    assert kept.json()["version"]["alignment"]["table_present"] is True
