"""PostgreSQL 18 checks for entity bootstrap, RLS, and security_barrier views.

Skipped when the integration Postgres is not reachable. Does not start Docker.
Uses a throwaway database. Role passwords that already exist are restored.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
import time
import uuid

import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Connection, make_url
from sqlalchemy.exc import ProgrammingError

from backend.entity.bootstrap import run_bootstrap
from backend.entity.ddl import (
    ACL_OWNER_ROLE,
    ENTITY_OWNER_ROLE,
    EXPOSURE_OWNER_ROLE,
    READER_ROLE,
    table_security_statements,
)

pytestmark = pytest.mark.integration

_MAINTENANCE_DATABASE_URL = os.getenv(
    "REFRAQ_INTEGRATION_MAINTENANCE_DATABASE_URL",
    "postgresql+psycopg://refraq:refraq@127.0.0.1:5432/refraq",
)
_ROLES = (ENTITY_OWNER_ROLE, EXPOSURE_OWNER_ROLE, ACL_OWNER_ROLE, READER_ROLE)
_OWNER_PASSWORD = "owner-secret"
_READER_PASSWORD = "reader-secret"


def _postgres_available() -> bool:
    try:
        engine = create_engine(_MAINTENANCE_DATABASE_URL)
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        engine.dispose()
        return True
    except Exception:
        return False


def _url(database: str, *, username: str, password: str) -> str:
    return make_url(_MAINTENANCE_DATABASE_URL).set(
        database=database, username=username, password=password
    ).render_as_string(hide_password=False)


def _snapshot(conn: Connection) -> dict[str, str | None]:
    rows = conn.execute(
        text("SELECT rolname, rolpassword FROM pg_authid WHERE rolname = ANY(:names)"),
        {"names": list(_ROLES)},
    ).all()
    return {str(name): password for name, password in rows}


def _restore(conn: Connection, before: dict[str, str | None]) -> None:
    for name in _ROLES:
        if name not in before:
            conn.execute(text(f'ALTER ROLE "{name}" WITH NOLOGIN PASSWORD NULL'))
            continue
        conn.execute(
            text("UPDATE pg_authid SET rolpassword = :password WHERE rolname = :name"),
            {"name": name, "password": before[name]},
        )


def _sign(secret: bytes, payload: dict[str, object]) -> str:
    body = json.dumps(payload, separators=(",", ":")).encode()
    digest = hmac.new(secret, body, hashlib.sha256).hexdigest()
    return base64.b64encode(body).decode("ascii") + "." + digest


def test_bootstrap_is_idempotent_and_reader_cannot_bypass_rls() -> None:
    if not _postgres_available():
        pytest.skip("Postgres not available (start: docker compose up -d)")

    maintenance = create_engine(_MAINTENANCE_DATABASE_URL, isolation_level="AUTOCOMMIT")
    database = f"refraq_eacl_{uuid.uuid4().hex[:8]}"
    admin_url = _url(database, username="refraq", password=make_url(_MAINTENANCE_DATABASE_URL).password or "")
    before: dict[str, str | None] = {}
    try:
        with maintenance.connect() as conn:
            version = int(conn.execute(text("SHOW server_version_num")).scalar_one())
            if version < 180000:
                pytest.skip(f"PostgreSQL server_version_num={version} is older than 18")
            before = _snapshot(conn)
            conn.execute(text(f'CREATE DATABASE "{database}"'))
        owner_url = _url(
            database, username=ENTITY_OWNER_ROLE, password=_OWNER_PASSWORD
        )
        reader_url = _url(database, username=READER_ROLE, password=_READER_PASSWORD)
        first = run_bootstrap(admin_url, owner_url, reader_url)
        assert first.database == database
        assert first.moved == 0

        admin = create_engine(admin_url)
        physical = "widget__v1__0123456789abcdef"
        try:
            with admin.begin() as conn:
                conn.execute(
                    text(
                        f'CREATE TABLE public."{physical}" '
                        "(row_id bigint generated by default as identity primary key, secret text)"
                    )
                )
                conn.execute(
                    text(f'INSERT INTO public."{physical}" (secret) VALUES (:secret)'),
                    {"secret": "kept"},
                )
                conn.execute(
                    text(
                        f'CREATE VIEW public.widget AS SELECT * FROM public."{physical}"'
                    )
                )
                conn.execute(
                    text("CREATE TABLE public.not_entity (id int)")
                )
        finally:
            admin.dispose()

        second = run_bootstrap(admin_url, owner_url, reader_url)
        assert second.moved == 2
        third = run_bootstrap(admin_url, owner_url, reader_url)
        assert third.moved == 0
        assert third.secured_tables >= 1

        _assert_moved_and_closed(admin_url, reader_url, owner_url, physical)
        leakproof = _leakproof_operators(admin_url)
        assert ("text", "=") in leakproof
        _assert_barrier_not_pierced(admin_url, reader_url)
    finally:
        with maintenance.connect() as conn:
            try:
                conn.execute(
                    text(
                        "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                        "WHERE datname = :name AND pid <> pg_backend_pid()"
                    ),
                    {"name": database},
                )
                conn.execute(text(f'DROP DATABASE IF EXISTS "{database}"'))
            finally:
                if before:
                    _restore(conn, before)
        maintenance.dispose()


def _assert_moved_and_closed(
    admin_url: str, reader_url: str, owner_url: str, physical: str
) -> None:
    admin = create_engine(admin_url)
    reader = create_engine(reader_url)
    owner = create_engine(owner_url)
    try:
        with admin.begin() as conn:
            count = conn.execute(
                text(f'SELECT count(*) FROM entity_data."{physical}"')
            ).scalar_one()
            assert int(count) == 1
            gone = conn.execute(
                text("SELECT to_regclass(:name)"),
                {"name": f'public."{physical}"'},
            ).scalar()
            assert gone is None
            secret = b"k" * 32
            conn.execute(
                text("SELECT acl.install_key(:kid, :secret)"),
                {"kid": "k1", "secret": secret},
            )
        payload = {
            "sub": "user_1",
            "grants": ["g1"],
            "attrs": {"dept": "eng"},
            "rev": {"ent_a": 3},
            "exp": int(time.time()) + 3600,
            "req": "req_1",
            "kid": "k1",
        }
        good = _sign(secret, payload)
        bad = good[:-4] + "0000"
        with reader.connect() as conn:
            who = conn.execute(text("SELECT current_user")).scalar_one()
            assert who == READER_ROLE
            conn.execute(text("RESET ROLE"))
            assert conn.execute(text("SELECT current_user")).scalar_one() == READER_ROLE
            with pytest.raises(ProgrammingError):
                conn.execute(text("SET ROLE refraq_entity_owner"))
            conn.rollback()
            with pytest.raises(ProgrammingError, match="permission denied"):
                conn.execute(text(f'SELECT secret FROM entity_data."{physical}"'))
            conn.rollback()
            with pytest.raises(ProgrammingError, match="permission denied"):
                conn.execute(text("SELECT * FROM public.not_entity"))
            conn.rollback()
            conn.execute(text("SELECT set_config('app.ctx', :token, true)"), {"token": bad})
            assert conn.execute(text("SELECT acl.grant_active('g1')")).scalar_one() is False
            assert conn.execute(text("SELECT acl.rev_ok('ent_a', 3)")).scalar_one() is False
            assert conn.execute(text("SELECT acl.subject_text('dept')")).scalar_one() is None
            conn.execute(text("SELECT set_config('app.ctx', :token, true)"), {"token": good})
            assert conn.execute(text("SELECT acl.grant_active('g1')")).scalar_one() is True
            assert conn.execute(text("SELECT acl.grant_active('other')")).scalar_one() is False
            assert conn.execute(text("SELECT acl.rev_ok('ent_a', 3)")).scalar_one() is True
            assert conn.execute(text("SELECT acl.rev_ok('ent_a', 2)")).scalar_one() is False
            assert conn.execute(text("SELECT acl.subject_text('dept')")).scalar_one() == "eng"
        with owner.begin() as conn:
            conn.execute(
                text(f'INSERT INTO entity_data."{physical}" (secret) VALUES (\'via-owner\')')
            )
            written = conn.execute(
                text(f'SELECT count(*) FROM entity_data."{physical}" WHERE secret = \'via-owner\'')
            ).scalar_one()
            assert int(written) == 1
    finally:
        reader.dispose()
        owner.dispose()
        admin.dispose()


def _assert_barrier_not_pierced(admin_url: str, reader_url: str) -> None:
    admin = create_engine(admin_url)
    reader = create_engine(reader_url)
    try:
        with admin.begin() as conn:
            conn.execute(
                text(
                    "CREATE TABLE entity_data.rls_probe ("
                    "row_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    "secret text)"
                )
            )
            for sql in table_security_statements("entity_data", "rls_probe"):
                conn.exec_driver_sql(sql)
            conn.execute(
                text(
                    "INSERT INTO entity_data.rls_probe (secret) VALUES ('boom'), ('visible')"
                )
            )
            conn.execute(
                text(
                    "CREATE VIEW entity_access.rls_probe_v "
                    "WITH (security_barrier = true, security_invoker = false) AS "
                    "SELECT row_id, secret, current_user AS who "
                    "FROM entity_data.rls_probe"
                )
            )
            conn.execute(
                text(
                    'ALTER VIEW entity_access.rls_probe_v OWNER TO "refraq_exposure_owner"'
                )
            )
            conn.execute(
                text('GRANT SELECT ON entity_access.rls_probe_v TO "refraq_reader"')
            )
            conn.execute(
                text(
                    "CREATE VIEW entity_access.rls_barrier "
                    "WITH (security_barrier = true, security_invoker = false) AS "
                    "SELECT row_id, shown FROM ("
                    "  SELECT t.row_id, "
                    "         CASE WHEN t.row_id % 2 = 0 THEN t.secret ELSE NULL END AS shown, "
                    "         (t.row_id % 2 = 0) AS guard "
                    "  FROM entity_data.rls_probe t"
                    ") s WHERE guard"
                )
            )
            conn.execute(
                text(
                    'ALTER VIEW entity_access.rls_barrier OWNER TO "refraq_exposure_owner"'
                )
            )
            conn.execute(
                text('GRANT SELECT ON entity_access.rls_barrier TO "refraq_reader"')
            )
            conn.execute(text("CREATE SCHEMA probe"))
            conn.execute(text('GRANT USAGE ON SCHEMA probe TO "refraq_reader"'))
            conn.execute(
                text(
                    "CREATE FUNCTION probe.leak(v text) RETURNS boolean "
                    "LANGUAGE plpgsql AS $fn$ "
                    "BEGIN "
                    "  IF v = 'boom' THEN RAISE EXCEPTION 'leaked'; END IF; "
                    "  RETURN true; "
                    "END $fn$"
                )
            )
            conn.execute(text('GRANT EXECUTE ON FUNCTION probe.leak(text) TO "refraq_reader"'))
            conn.execute(text('GRANT USAGE ON SCHEMA entity_data TO "refraq_reader"'))
            conn.execute(
                text('GRANT SELECT ON entity_data.rls_probe TO "refraq_reader"')
            )
        with reader.connect() as conn:
            rows = conn.execute(
                text("SELECT secret, who FROM entity_access.rls_probe_v ORDER BY row_id")
            ).all()
            assert [row[0] for row in rows] == ["boom", "visible"]
            assert {row[1] for row in rows} == {READER_ROLE}
            hidden = conn.execute(
                text("SELECT count(*) FROM entity_data.rls_probe")
            ).scalar_one()
            assert int(hidden) == 0
            seen = conn.execute(
                text(
                    "SELECT shown FROM entity_access.rls_barrier "
                    "WHERE probe.leak(shown)"
                )
            ).scalars().all()
            assert seen == ["visible"]
            plan = conn.execute(
                text(
                    "EXPLAIN (FORMAT JSON) SELECT shown FROM entity_access.rls_barrier "
                    "WHERE probe.leak(shown)"
                )
            ).scalar_one()
        _assert_leak_not_on_base_scan(plan)
        with admin.begin() as conn:
            conn.execute(
                text('REVOKE SELECT ON entity_data.rls_probe FROM "refraq_reader"')
            )
            conn.execute(text('REVOKE USAGE ON SCHEMA entity_data FROM "refraq_reader"'))
    finally:
        reader.dispose()
        admin.dispose()


def _assert_leak_not_on_base_scan(plan: object) -> None:
    document = json.loads(plan) if isinstance(plan, str) else plan
    nodes: list[dict[str, object]] = []

    def walk(node: dict[str, object]) -> None:
        nodes.append(node)
        for child in node.get("Plans") or []:
            if isinstance(child, dict):
                walk(child)

    root = document[0]["Plan"]
    assert isinstance(root, dict)
    walk(root)
    scans = [node for node in nodes if node.get("Relation Name") == "rls_probe"]
    assert scans, plan
    for scan in scans:
        blob = json.dumps(
            {key: scan.get(key) for key in ("Filter", "Index Cond", "Recheck Cond")}
        )
        assert "leak" not in blob, plan
    assert any("leak" in json.dumps(node.get("Filter")) for node in nodes), plan


def _leakproof_operators(admin_url: str) -> dict[tuple[str, str], bool]:
    admin = create_engine(admin_url)
    try:
        with admin.connect() as conn:
            rows = conn.execute(
                text(
                    "SELECT tn.typname, o.oprname, bool_and(p.proleakproof) "
                    "FROM pg_operator o "
                    "JOIN pg_proc p ON p.oid = o.oprcode "
                    "JOIN pg_type tn ON tn.oid = o.oprleft "
                    "JOIN pg_type tr ON tr.oid = o.oprright "
                    "WHERE tn.oid = tr.oid "
                    "AND tn.typname IN ("
                    "'text','varchar','numeric','timestamptz','date','int8',"
                    "'float8','bool','time','jsonb'"
                    ") "
                    "AND o.oprname IN ('=','<>','<','<=','>','>=','~~','~~*') "
                    "GROUP BY tn.typname, o.oprname"
                )
            ).all()
    finally:
        admin.dispose()
    return {(str(typ), str(op)): bool(flag) for typ, op, flag in rows}
