"""Entity publish create and drop Job tests against a recording DDL port."""

from __future__ import annotations

import os
from dataclasses import replace

import pytest
from fastapi.testclient import TestClient

os.environ["REFRAQ_STORE_BACKEND"] = "memory"
os.environ["REFRAQ_SECRETS_MASTER_KEY"] = "test-secrets-master-key"
os.environ["CELERY_TASK_ALWAYS_EAGER"] = "1"
os.environ.pop("DATABASE_URL", None)
os.environ.pop("REDIS_URL", None)
os.environ.setdefault("CELERY_BROKER_URL", "memory://")

from backend.admin.audit_store import get_audit_store  # noqa: E402
from backend.admin.roles import seed_roles  # noqa: E402
from backend.admin.role_store import get_role_store  # noqa: E402
from backend.admin.security import hash_password  # noqa: E402
from backend.admin.user_store import get_user_store  # noqa: E402
from backend.core.time import utc_now  # noqa: E402
from backend.entity.jobs import find_inflight_entity_table_job  # noqa: E402
from backend.entity.table_name import compose_physical_table_name  # noqa: E402
from backend.entity.kinds import KIND_RECONCILE  # noqa: E402
from backend.entity.lifecycle import PUBLISHING  # noqa: E402
from backend.entity.locks import try_acquire_entity_table_lock  # noqa: E402
from backend.entity.store import get_entity_store  # noqa: E402
from backend.entity.tasks import run_job  # noqa: E402
from backend.entity.table_port import (  # noqa: E402
    EntityTableHasRows,
    RecordingEntityTablePort,
    bind_entity_table_port,
    get_entity_table_port,
    reset_entity_table_port,
)
from backend.jobs.store import create_queued_job, get_job_store  # noqa: E402
from backend.main import app  # noqa: E402
from backend.tests.test_entity import SKU, _create_body  # noqa: E402


@pytest.fixture()
def port() -> RecordingEntityTablePort:
    recording = RecordingEntityTablePort()
    bind_entity_table_port(recording)
    return recording


@pytest.fixture()
def client(port: RecordingEntityTablePort) -> TestClient:
    del port
    roles = get_role_store()
    seed_roles(roles)
    admin = roles.get_by_key("super_admin")
    assert admin is not None
    get_user_store().create_user(
        account="admin",
        display_name="Admin",
        password_hash=hash_password("secret"),
        role_id=admin.id,
        status="active",
    )
    with TestClient(app) as test_client:
        login = test_client.post(
            "/auth/login", json={"account": "admin", "password": "secret"}
        )
        assert login.status_code == 200, login.text
        yield test_client


def _create(client: TestClient) -> dict:
    created = client.post("/entities", json=_create_body())
    assert created.status_code == 201, created.text
    return created.json()["entity"]


def _publish(client: TestClient, entity: dict) -> dict:
    version_id = entity["current_version"]["id"]
    published = client.post(
        f"/entities/{entity['id']}/versions/{version_id}/publish"
    )
    assert published.status_code == 201, published.text
    return published.json()


def test_publish_creates_table_and_locks(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    published = _publish(client, entity)
    job = published["job"]
    assert job["kind"] == "entity_reconcile"
    assert job["status"] == "succeeded"
    assert job["result"]["schema"] == "entity_reconcile.v1"
    assert job["result"]["action"] == "created"
    assert job["result"]["columns_added"] == 1
    assert job["result"]["unique_added"] == 1
    physical, comment = compose_physical_table_name("material", 1, version_id)
    assert comment is None
    assert job["result"]["table_name"] == physical
    create_sql = port.statements[0]
    assert "CREATE TABLE" in create_sql
    assert f'"entity_data"."{physical}"' in create_sql
    assert any("ENABLE ROW LEVEL SECURITY" in stmt for stmt in port.statements)
    assert any("FORCE ROW LEVEL SECURITY" in stmt for stmt in port.statements)
    assert any(
        'OWNER TO "refraq_entity_owner"' in stmt for stmt in port.statements
    )
    assert '"row_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' in create_sql
    assert "UNIQUE" in create_sql
    assert any(
        "CREATE VIEW" in stmt and '"entity_data"."material"' in stmt for stmt in port.statements
    )

    detail = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    version = detail.json()["version"]
    assert version["publish_status"] == "published"
    assert version["table_name"] == physical
    assert not any(stmt.startswith("COMMENT") for stmt in port.statements)
    alignment = version["alignment"]
    assert alignment["table_present"] is True
    assert alignment["latest_job_id"] == job["id"]
    assert alignment["latest_job_status"] == "succeeded"

    events, _ = get_audit_store().list_events(action="entity.publish_enqueue")
    assert events

    second = client.post(f"/entities/{entity['id']}/versions/{version_id}/publish")
    assert second.status_code == 422
    assert second.json()["code"] == "ENTITY_NOT_UNPUBLISHED"


def test_long_stem_is_shortened_and_commented(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    stem = "a" * 63
    created = client.post("/entities", json=_create_body(table_name=stem))
    assert created.status_code == 201, created.text
    entity = created.json()["entity"]
    version_id = entity["current_version"]["id"]
    published = _publish(client, entity)
    assert published["job"]["status"] == "succeeded"
    physical, comment = compose_physical_table_name(stem, 1, version_id)
    assert comment == stem
    assert len(physical) == 63
    assert physical.endswith(f"__v1__{version_id}")
    assert any(
        stmt.startswith("COMMENT ON TABLE") and f"'{stem}'" in stmt
        for stmt in port.statements
    )
    detail = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    assert detail.json()["version"]["table_name"] == physical


def test_publish_successor_repoints_stem_view(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    entity = _create(client)
    v1 = entity["current_version"]["id"]
    _publish(client, entity)
    opened = client.post(f"/entities/{entity['id']}/versions", json={})
    assert opened.status_code == 201
    v2 = opened.json()["version"]["id"]
    v1_physical, _v1_comment = compose_physical_table_name("material", 1, v1)
    v2_physical, _v2_comment = compose_physical_table_name("material", 2, v2)
    live = client.get(f"/entities/{entity['id']}/versions/{v1}")
    assert live.json()["version"]["table_name"] == v1_physical
    current = client.get(f"/entities/{entity['id']}").json()["entity"]
    _publish(client, current)
    kept = client.get(f"/entities/{entity['id']}/versions/{v1}")
    assert kept.json()["version"]["table_name"] == v1_physical
    successor = client.get(f"/entities/{entity['id']}/versions/{v2}")
    assert successor.json()["version"]["table_name"] == v2_physical
    assert not any("RENAME TO" in stmt for stmt in port.statements)
    assert any(
        "CREATE VIEW" in stmt and f'"entity_data"."{v2_physical}"' in stmt
        for stmt in port.statements
    )

    dropped = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert dropped.status_code == 201, dropped.text
    job = get_job_store().get(dropped.json()["job"]["id"])
    assert job is not None
    assert job.status == "succeeded"


def test_publish_name_conflict_rolls_back(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    port.create_physical_table("entity_data", "material", [])
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    published = client.post(
        f"/entities/{entity['id']}/versions/{version_id}/publish"
    )
    assert published.status_code == 201
    job = get_job_store().get(published.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "ENTITY_TABLE_NAME_CONFLICT"
    version = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    assert version.json()["version"]["publish_status"] == "unpublished"
    assert version.json()["version"]["alignment"]["table_present"] is False


def _defer_publish(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(
        "backend.entity.jobs.dispatch_entity_job", lambda job: job.id
    )


def _code_list(client: TestClient) -> str:
    created = client.post(
        "/dictionaries",
        json={
            "name": "order_status",
            "display_name": "Order status",
            "entries": [
                {"code": "open", "label": "Open", "active": True},
                {"code": "closed", "label": "Closed", "active": True},
            ],
        },
    )
    assert created.status_code == 201, created.text
    return created.json()["dictionary"]["id"]


def _entity_on_dictionary(client: TestClient, dictionary_id: str) -> tuple[dict, dict]:
    attribute = {
        "name": "status",
        "type": "dictionary",
        "description": "Order status",
        "config": {"dictionary_id": dictionary_id},
    }
    created = client.post(
        "/entities",
        json={
            "table_name": "orders",
            "name": "Orders",
            "description": "Customer orders.",
            "attributes": [attribute],
        },
    )
    assert created.status_code == 201, created.text
    return created.json()["entity"], attribute


def _patch_dictionary(client: TestClient, dictionary_id: str, body: dict) -> dict:
    patched = client.patch(f"/dictionaries/{dictionary_id}", json=body)
    assert patched.status_code == 200, patched.text
    return patched.json()["dictionary"]


def test_publish_without_frozen_bindings_fails_closed(
    client: TestClient,
    port: RecordingEntityTablePort,
) -> None:
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    queued = create_queued_job(
        kind=KIND_RECONCILE,
        input={"entity_version_id": version_id},
        created_by="user_admin",
        trigger_kind="user",
        trigger_ref="user_admin",
    )
    store = get_entity_store()
    version = store.get_version(version_id)
    assert version is not None
    store.save_version(
        replace(
            version,
            publish_status=PUBLISHING,
            latest_reconcile_job_id=queued.id,
            updated_at=utc_now(),
        )
    )
    assert run_job(queued.id)["status"] == "failed"
    job = get_job_store().get(queued.id)
    assert job is not None
    assert job.error_code == "JOB_INPUT_INVALID"
    physical, _comment = compose_physical_table_name("material", 1, version_id)
    assert port.table_exists("entity_data", physical) is False
    read = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    body = read.json()["version"]
    assert body["publish_status"] == "unpublished"
    assert body["alignment"]["table_present"] is False


@pytest.mark.parametrize(
    "change",
    ["subset", "added", "cleared", "deprecated"],
)
def test_publish_rejects_dictionary_change_after_accept(
    client: TestClient,
    port: RecordingEntityTablePort,
    monkeypatch: pytest.MonkeyPatch,
    change: str,
) -> None:
    dictionary_id = _code_list(client)
    entity, attribute = _entity_on_dictionary(client, dictionary_id)
    version_id = entity["current_version"]["id"]
    _defer_publish(monkeypatch)
    queued = client.post(f"/entities/{entity['id']}/versions/{version_id}/publish")
    assert queued.status_code == 201, queued.text
    job_id = queued.json()["job"]["id"]
    if change == "subset":
        _patch_dictionary(
            client,
            dictionary_id,
            {
                "entries": [
                    {"code": "open", "label": "Open", "active": True},
                    {"code": "closed", "label": "Closed", "active": False},
                ]
            },
        )
    elif change == "added":
        _patch_dictionary(
            client,
            dictionary_id,
            {
                "entries": [
                    {"code": "open", "label": "Open", "active": True},
                    {"code": "closed", "label": "Closed", "active": True},
                    {"code": "held", "label": "Held", "active": True},
                ]
            },
        )
    elif change == "cleared":
        _patch_dictionary(
            client,
            dictionary_id,
            {
                "entries": [
                    {"code": "open", "label": "Open", "active": False},
                    {"code": "closed", "label": "Closed", "active": False},
                ]
            },
        )
    else:
        _patch_dictionary(client, dictionary_id, {"deprecated": True})
    assert run_job(job_id)["status"] == "failed"
    job = get_job_store().get(job_id)
    assert job is not None
    assert job.error_code == "ENTITY_ATTRIBUTE_INVALID"
    summary = job.error_summary or ""
    assert summary.startswith("Dictionary changed after publish was accepted")
    assert "accepted=[open, closed]" in summary
    if change == "subset":
        assert "now=[open]" in summary
    elif change == "added":
        assert "now=[open, closed, held]" in summary
    elif change == "cleared":
        assert "now=[]" in summary
    else:
        assert "now=[open, closed]" in summary
        assert "deprecated" in summary
    physical, _comment = compose_physical_table_name("orders", 1, version_id)
    assert port.table_exists("entity_data", physical) is False
    read = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    body = read.json()["version"]
    assert body["publish_status"] == "unpublished"
    assert body["alignment"]["table_present"] is False
    if change != "cleared":
        return
    saved = client.patch(
        f"/entities/{entity['id']}/versions/{version_id}",
        json={
            "attributes": [{**attribute, "description": "Status after a failed publish"}]
        },
    )
    assert saved.status_code == 200, saved.text
    again = client.post(f"/entities/{entity['id']}/versions/{version_id}/publish")
    assert again.status_code == 422
    assert again.json()["code"] == "ENTITY_ATTRIBUTE_INVALID"
    _records, total = get_job_store().list(kind=KIND_RECONCILE)
    assert total == 1
    deleted = client.delete(f"/entities/{entity['id']}")
    assert deleted.status_code == 204


@pytest.mark.parametrize(
    "change",
    ["label", "restored", "already_deprecated", "undeprecated"],
)
def test_publish_keeps_frozen_codes_when_dictionary_still_matches(
    client: TestClient,
    port: RecordingEntityTablePort,
    monkeypatch: pytest.MonkeyPatch,
    change: str,
) -> None:
    dictionary_id = _code_list(client)
    entity, _attribute = _entity_on_dictionary(client, dictionary_id)
    version_id = entity["current_version"]["id"]
    if change == "already_deprecated":
        _patch_dictionary(client, dictionary_id, {"deprecated": True})
    _defer_publish(monkeypatch)
    queued = client.post(f"/entities/{entity['id']}/versions/{version_id}/publish")
    assert queued.status_code == 201, queued.text
    job_id = queued.json()["job"]["id"]
    if change == "label":
        _patch_dictionary(
            client,
            dictionary_id,
            {
                "entries": [
                    {"code": "open", "label": "Opened", "active": True},
                    {"code": "closed", "label": "Shut", "active": True},
                ]
            },
        )
    elif change == "restored":
        _patch_dictionary(
            client,
            dictionary_id,
            {"entries": [{"code": "open", "label": "Open", "active": True}]},
        )
        _patch_dictionary(
            client,
            dictionary_id,
            {
                "entries": [
                    {"code": "closed", "label": "Closed", "active": True},
                    {"code": "open", "label": "Open", "active": True},
                ]
            },
        )
    elif change == "undeprecated":
        _patch_dictionary(client, dictionary_id, {"deprecated": True})
        _patch_dictionary(client, dictionary_id, {"deprecated": False})
    assert run_job(job_id)["status"] == "succeeded"
    stored = get_entity_store().get_version(version_id)
    assert stored is not None
    snapshot = stored.dictionary_snapshots["status"]
    assert snapshot["codes"] == ["open", "closed"]
    detail = client.get(f"/dictionaries/{dictionary_id}")
    assert snapshot["revision"] == detail.json()["dictionary"]["revision"]
    check = next(sql for sql in port.statements if "CHECK" in sql)
    assert "'open', 'closed'" in check


def test_delete_while_first_publish_names_publishing(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(
        "backend.entity.jobs.dispatch_entity_job", lambda job: job.id
    )
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    queued = client.post(f"/entities/{entity['id']}/versions/{version_id}/publish")
    assert queued.status_code == 201, queued.text
    refused = client.delete(f"/entities/{entity['id']}")
    assert refused.status_code == 422
    body = refused.json()
    assert body["code"] == "ENTITY_PUBLISHING"
    assert body["detail"] == "A publishing version refuses writes"


def test_delete_while_successor_publishing_names_publishing(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    entity = _create(client)
    _publish(client, entity)
    opened = client.post(f"/entities/{entity['id']}/versions", json={})
    assert opened.status_code == 201, opened.text
    version_id = opened.json()["version"]["id"]
    monkeypatch.setattr(
        "backend.entity.jobs.dispatch_entity_job", lambda job: job.id
    )
    queued = client.post(f"/entities/{entity['id']}/versions/{version_id}/publish")
    assert queued.status_code == 201, queued.text
    refused = client.delete(f"/entities/{entity['id']}")
    assert refused.status_code == 422
    body = refused.json()
    assert body["code"] == "ENTITY_PUBLISHING"
    assert body["detail"] == "A publishing version refuses writes"


def test_revert_failure_is_logged_and_original_error_kept(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    class _RevertFails(RecordingEntityTablePort):
        def revert_physical_table(self, schema: str, table: str) -> None:
            del schema, table
            raise RuntimeError("archive restore failed")

    bind_entity_table_port(_RevertFails())

    def _snapshot_fails(attributes: list) -> list:
        del attributes
        raise RuntimeError("snapshot write failed")

    monkeypatch.setattr(
        "backend.entity.publish.attribute_to_dict", _snapshot_fails
    )
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    published = client.post(
        f"/entities/{entity['id']}/versions/{version_id}/publish"
    )
    assert published.status_code == 201, published.text
    job = get_job_store().get(published.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "JOB_EXECUTION_FAILED"
    assert "snapshot write failed" in (job.error_summary or "")
    assert "revert failed: archive restore failed" in job.log_body


def test_revert_with_rows_logs_that_the_table_was_left(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    class _RevertHasRows(RecordingEntityTablePort):
        def revert_physical_table(self, schema: str, table: str) -> None:
            raise EntityTableHasRows(f"{schema}.{table}")

    bind_entity_table_port(_RevertHasRows())

    def _snapshot_fails(attributes: list) -> list:
        del attributes
        raise RuntimeError("snapshot write failed")

    monkeypatch.setattr("backend.entity.publish.attribute_to_dict", _snapshot_fails)
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    published = client.post(
        f"/entities/{entity['id']}/versions/{version_id}/publish"
    )
    assert published.status_code == 201, published.text
    job = get_job_store().get(published.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "JOB_EXECUTION_FAILED"
    physical, _comment = compose_physical_table_name("material", 1, version_id)
    assert f"entity_data.{physical} has rows and was left in place" in job.log_body
    assert " WARN " in job.log_body
    bound = get_entity_table_port()
    assert bound.table_exists("entity_data", physical) is True
    version = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    assert version.json()["version"]["publish_status"] == "unpublished"


def test_stem_view_failure_never_stores_published(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    statuses: list[str] = []
    store = get_entity_store()
    original = store.save_version

    def spy(version):
        statuses.append(version.publish_status)
        return original(version)

    monkeypatch.setattr(store, "save_version", spy)

    class _SwapFails(RecordingEntityTablePort):
        def swap_stem_view(
            self,
            schema: str,
            stem: str,
            *,
            physical: str,
            expected_target: str | None,
        ) -> None:
            del schema, stem, physical, expected_target
            raise RuntimeError("view swap failed")

    failing = _SwapFails()
    bind_entity_table_port(failing)
    published = client.post(
        f"/entities/{entity['id']}/versions/{version_id}/publish"
    )
    assert published.status_code == 201, published.text
    job = get_job_store().get(published.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "JOB_EXECUTION_FAILED"
    assert "published" not in statuses
    assert statuses == ["publishing", "unpublished"]
    physical, _comment = compose_physical_table_name("material", 1, version_id)
    assert failing.table_exists("entity_data", physical) is False
    assert ("entity_data", "material") not in failing._views
    version = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    assert version.json()["version"]["publish_status"] == "unpublished"


def test_metadata_failure_after_swap_restores_stem_view(
    client: TestClient,
    port: RecordingEntityTablePort,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from backend.entity.records import attribute_to_dict

    armed = {"on": False}
    real = attribute_to_dict

    def wrapped(attr):
        if armed["on"]:
            raise RuntimeError("snapshot write failed")
        return real(attr)

    monkeypatch.setattr("backend.entity.publish.attribute_to_dict", wrapped)
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    armed["on"] = True
    failed = client.post(f"/entities/{entity['id']}/versions/{version_id}/publish")
    assert failed.status_code == 201, failed.text
    job = get_job_store().get(failed.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert ("entity_data", "material") not in port._views
    failed_version = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    assert failed_version.json()["version"]["publish_status"] == "unpublished"

    armed["on"] = False
    succeeded = _publish(client, entity)
    assert succeeded["job"]["status"] == "succeeded"
    v1_physical, _comment = compose_physical_table_name("material", 1, version_id)
    assert port._views[("entity_data", "material")] == v1_physical

    opened = client.post(f"/entities/{entity['id']}/versions", json={})
    assert opened.status_code == 201, opened.text
    v2 = opened.json()["version"]["id"]
    armed["on"] = True
    current = client.get(f"/entities/{entity['id']}").json()["entity"]
    successor = _publish(client, current)
    assert successor["job"]["status"] == "failed"
    assert port._views[("entity_data", "material")] == v1_physical
    successor_version = client.get(f"/entities/{entity['id']}/versions/{v2}")
    assert successor_version.json()["version"]["publish_status"] == "unpublished"
    head = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    assert head.json()["version"]["publish_status"] == "published"


def test_restore_view_failure_keeps_table_and_names_the_failure(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    class _DropViewFails(RecordingEntityTablePort):
        def __init__(self) -> None:
            super().__init__()
            self.reverts = 0

        def drop_stem_view(self, schema: str, stem: str) -> None:
            del schema, stem
            raise RuntimeError("view restore failed")

        def revert_physical_table(self, schema: str, table: str) -> None:
            self.reverts += 1
            super().revert_physical_table(schema, table)

    failing = _DropViewFails()
    bind_entity_table_port(failing)

    def _snapshot_fails(attr: object) -> object:
        del attr
        raise RuntimeError("snapshot write failed")

    monkeypatch.setattr("backend.entity.publish.attribute_to_dict", _snapshot_fails)
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    published = client.post(
        f"/entities/{entity['id']}/versions/{version_id}/publish"
    )
    assert published.status_code == 201, published.text
    job = get_job_store().get(published.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "JOB_EXECUTION_FAILED"
    summary = job.error_summary or ""
    assert "snapshot write failed" in summary
    assert "restore view failed: view restore failed" in summary
    physical, _comment = compose_physical_table_name("material", 1, version_id)
    assert failing.table_exists("entity_data", physical) is True
    assert failing.reverts == 0
    version = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    assert version.json()["version"]["publish_status"] == "unpublished"


def test_successor_restore_swap_failure_leaves_new_table(
    client: TestClient,
    port: RecordingEntityTablePort,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from backend.entity.records import attribute_to_dict

    entity = _create(client)
    version_id = entity["current_version"]["id"]
    _publish(client, entity)
    opened = client.post(f"/entities/{entity['id']}/versions", json={})
    assert opened.status_code == 201, opened.text
    v2 = opened.json()["version"]["id"]

    class _SecondSwapFails(RecordingEntityTablePort):
        def __init__(self) -> None:
            super().__init__()
            self.swaps = 0
            self.reverts = 0

        def swap_stem_view(
            self,
            schema: str,
            stem: str,
            *,
            physical: str,
            expected_target: str | None,
        ) -> None:
            self.swaps += 1
            if self.swaps > 1:
                raise RuntimeError("view restore failed")
            super().swap_stem_view(
                schema,
                stem,
                physical=physical,
                expected_target=expected_target,
            )

        def revert_physical_table(self, schema: str, table: str) -> None:
            self.reverts += 1
            super().revert_physical_table(schema, table)

    failing = _SecondSwapFails()
    failing.statements = port.statements
    failing._tables = port._tables
    failing._views = port._views
    bind_entity_table_port(failing)

    armed = {"on": False}
    real = attribute_to_dict

    def wrapped(attr):
        if armed["on"]:
            raise RuntimeError("snapshot write failed")
        return real(attr)

    monkeypatch.setattr("backend.entity.publish.attribute_to_dict", wrapped)
    armed["on"] = True
    current = client.get(f"/entities/{entity['id']}").json()["entity"]
    successor = _publish(client, current)
    job = get_job_store().get(successor["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert "restore view failed: view restore failed" in (job.error_summary or "")
    v2_physical, _comment = compose_physical_table_name("material", 2, v2)
    assert failing._views[("entity_data", "material")] == v2_physical
    assert failing.table_exists("entity_data", v2_physical) is True
    assert failing.reverts == 0
    successor_version = client.get(f"/entities/{entity['id']}/versions/{v2}")
    assert successor_version.json()["version"]["publish_status"] == "unpublished"
    head = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    assert head.json()["version"]["publish_status"] == "published"


def test_save_refused_after_publish(client: TestClient) -> None:
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    _publish(client, entity)
    refused = client.patch(
        f"/entities/{entity['id']}/versions/{version_id}",
        json={"attributes": [SKU, {**SKU, "name": "note", "required": False}]},
    )
    assert refused.status_code == 422
    assert refused.json()["code"] == "ENTITY_NOT_UNPUBLISHED"


def test_inflight_publish_is_returned_not_duplicated(client: TestClient) -> None:
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    queued = create_queued_job(
        kind=KIND_RECONCILE,
        input={"entity_version_id": version_id},
        created_by="user_admin",
        trigger_kind="user",
        trigger_ref="user_admin",
    )
    store = get_entity_store()
    version = store.get_version(version_id)
    assert version is not None
    store.save_version(
        replace(
            version,
            publish_status=PUBLISHING,
            latest_reconcile_job_id=queued.id,
            updated_at=utc_now(),
        )
    )
    again = client.post(f"/entities/{entity['id']}/versions/{version_id}/publish")
    assert again.status_code == 200
    assert again.json()["job"]["id"] == queued.id
    records, _ = get_job_store().list(kind=KIND_RECONCILE)
    assert len(records) == 1


def test_drop_current_refused_until_deprecated(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    entity = _create(client)
    v1 = entity["current_version"]["id"]
    _publish(client, entity)
    current_drop = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert current_drop.status_code == 422
    assert current_drop.json()["code"] == "ENTITY_TABLE_IN_SERVICE"
    assert "superseded" not in current_drop.json()["detail"].lower()

    opened = client.post(f"/entities/{entity['id']}/versions", json={})
    assert opened.status_code == 201
    present_delete = client.delete(f"/entities/{entity['id']}")
    assert present_delete.status_code == 409
    assert present_delete.json()["code"] == "ENTITY_ALREADY_PUBLISHED"

    still_live = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert still_live.status_code == 422
    assert still_live.json()["code"] == "ENTITY_TABLE_IN_SERVICE"
    assert "superseded" not in still_live.json()["detail"].lower()

    assert client.post(f"/entities/{entity['id']}/deprecate").status_code == 200
    dropped = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert dropped.status_code == 201, dropped.text
    job = get_job_store().get(dropped.json()["job"]["id"])
    assert job is not None
    assert job.status == "succeeded"
    assert job.result["schema"] == "entity_table_drop.v1"
    assert any("DROP TABLE" in stmt for stmt in port.statements)

    already = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert already.status_code == 200
    assert already.json()["job"] is None


def test_drop_current_after_deprecate(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    entity = _create(client)
    v1 = entity["current_version"]["id"]
    _publish(client, entity)
    assert client.post(f"/entities/{entity['id']}/deprecate").status_code == 200
    dropped = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert dropped.status_code == 201, dropped.text
    job = get_job_store().get(dropped.json()["job"]["id"])
    assert job is not None
    assert job.status == "succeeded"


def test_drop_non_empty_table_fails_job(
    client: TestClient, port: RecordingEntityTablePort
) -> None:
    class _NonEmpty(RecordingEntityTablePort):
        def drop_table(self, schema: str, table: str) -> None:
            raise EntityTableHasRows(f"{schema}.{table}")

    occupied = _NonEmpty()
    occupied.statements = port.statements
    occupied._tables = port._tables
    bind_entity_table_port(occupied)
    entity = _create(client)
    v1 = entity["current_version"]["id"]
    _publish(client, entity)
    assert client.post(f"/entities/{entity['id']}/versions", json={}).status_code == 201
    current = client.get(f"/entities/{entity['id']}").json()["entity"]
    _publish(client, current)
    dropped = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert dropped.status_code == 201
    job = get_job_store().get(dropped.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "ENTITY_TABLE_NOT_EMPTY"
    version = client.get(f"/entities/{entity['id']}/versions/{v1}")
    assert version.json()["version"]["alignment"]["table_present"] is True


def test_drop_lock_contention_leaves_published_version(client: TestClient) -> None:
    entity = _create(client)
    v1 = entity["current_version"]["id"]
    _publish(client, entity)
    opened = client.post(f"/entities/{entity['id']}/versions", json={})
    assert opened.status_code == 201
    current = client.get(f"/entities/{entity['id']}").json()["entity"]
    _publish(client, current)
    physical, _comment = compose_physical_table_name("material", 1, v1)
    held = try_acquire_entity_table_lock(entity["id"])
    assert held is not None
    try:
        dropped = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
        assert dropped.status_code == 201, dropped.text
        job = get_job_store().get(dropped.json()["job"]["id"])
        assert job is not None
        assert job.status == "failed"
        assert job.error_code == "JOB_ALREADY_ACTIVE"
        version = client.get(f"/entities/{entity['id']}/versions/{v1}")
        body = version.json()["version"]
        assert body["publish_status"] == "published"
        assert body["table_name"] == physical
    finally:
        held.release()


def test_publish_and_drop_share_lock(client: TestClient) -> None:
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    held = try_acquire_entity_table_lock(entity["id"])
    assert held is not None
    try:
        published = client.post(
            f"/entities/{entity['id']}/versions/{version_id}/publish"
        )
        assert published.status_code == 201
        job = get_job_store().get(published.json()["job"]["id"])
        assert job is not None
        assert job.status == "failed"
        assert job.error_code == "JOB_ALREADY_ACTIVE"
        version = client.get(f"/entities/{entity['id']}/versions/{version_id}")
        assert version.json()["version"]["publish_status"] == "unpublished"
    finally:
        held.release()
    assert find_inflight_entity_table_job(version_id) is None


class _PersistentNoEntityUrl:
    store_backend = "persistent"
    entity_database_url = None


def test_memory_without_bind_uses_recording() -> None:
    reset_entity_table_port()
    port = get_entity_table_port()
    assert isinstance(port, RecordingEntityTablePort)


def test_explicit_bind_wins_when_persistent_has_no_entity_url(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    recording = RecordingEntityTablePort()
    bind_entity_table_port(recording)
    monkeypatch.setattr(
        "backend.entity.table_port.get_settings", lambda: _PersistentNoEntityUrl()
    )
    assert get_entity_table_port() is recording


def test_persistent_without_entity_url_does_not_use_recording(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    reset_entity_table_port()
    monkeypatch.setattr(
        "backend.entity.table_port.get_settings", lambda: _PersistentNoEntityUrl()
    )
    with pytest.raises(ValueError, match="ENTITY_DATABASE_URL"):
        get_entity_table_port()


def test_persistent_publish_without_entity_url_fails_and_rolls_back(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    reset_entity_table_port()
    monkeypatch.setattr(
        "backend.entity.table_port.get_settings", lambda: _PersistentNoEntityUrl()
    )
    entity = _create(client)
    version_id = entity["current_version"]["id"]
    published = client.post(
        f"/entities/{entity['id']}/versions/{version_id}/publish"
    )
    assert published.status_code == 201, published.text
    job = get_job_store().get(published.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "JOB_EXECUTION_FAILED"
    assert "ENTITY_DATABASE_URL" in (job.error_summary or "")
    version = client.get(f"/entities/{entity['id']}/versions/{version_id}")
    assert version.json()["version"]["publish_status"] == "unpublished"
    alignment = version.json()["version"]["alignment"]
    assert alignment["table_present"] is False
    assert alignment["latest_job_status"] == "failed"


def test_persistent_drop_without_entity_url_fails_and_keeps_snapshot(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    entity = _create(client)
    v1 = entity["current_version"]["id"]
    store = get_entity_store()
    version = store.get_version(v1)
    assert version is not None
    store.save_version(
        replace(
            version,
            publish_status="published",
            materialized_attributes=[
                {
                    "name": "sku",
                    "type": "string",
                    "required": True,
                    "config": {"max_length": 32},
                }
            ],
            updated_at=utc_now(),
        )
    )
    assert client.post(f"/entities/{entity['id']}/deprecate").status_code == 200
    reset_entity_table_port()
    monkeypatch.setattr(
        "backend.entity.table_port.get_settings", lambda: _PersistentNoEntityUrl()
    )
    dropped = client.post(f"/entities/{entity['id']}/versions/{v1}/drop-table")
    assert dropped.status_code == 201, dropped.text
    job = get_job_store().get(dropped.json()["job"]["id"])
    assert job is not None
    assert job.status == "failed"
    assert job.error_code == "JOB_EXECUTION_FAILED"
    assert "ENTITY_DATABASE_URL" in (job.error_summary or "")
    kept = client.get(f"/entities/{entity['id']}/versions/{v1}")
    assert kept.json()["version"]["alignment"]["table_present"] is True
