/** Generated by scripts/gen_console_module_catalog.py — do not edit. */

import type { ModuleIdentity } from "@/features/console/module-identity/types";

export const GENERATED_MODULE_CATALOG: ModuleIdentity[] = [
  {
    "id": "dashboard",
    "label_key": "layout.nav.home",
    "routes": {
      "list": "/console",
      "create": null,
      "edit": null,
      "show": null,
      "aliases": []
    },
    "actions": {
      "list": "dashboard:read",
      "create": null,
      "edit": null,
      "delete": null,
      "show": null,
      "sample": null
    }
  },
  {
    "id": "users",
    "label_key": "users.title",
    "routes": {
      "list": "/console/users",
      "create": "/console/users/new",
      "edit": null,
      "show": null,
      "aliases": []
    },
    "actions": {
      "list": "users:read",
      "create": "users:write",
      "edit": "users:write",
      "delete": "users:write",
      "show": null,
      "sample": null
    }
  },
  {
    "id": "identity-providers",
    "label_key": "identityProviders.title",
    "routes": {
      "list": "/console/identity-providers",
      "create": null,
      "edit": null,
      "show": null,
      "aliases": []
    },
    "actions": {
      "list": "identity_providers:read",
      "create": "identity_providers:write",
      "edit": "identity_providers:write",
      "delete": "identity_providers:write",
      "show": null,
      "sample": null
    }
  },
  {
    "id": "roles",
    "label_key": "roles.title",
    "routes": {
      "list": "/console/roles",
      "create": "/console/roles/new",
      "edit": "/console/roles/:id",
      "show": null,
      "aliases": []
    },
    "actions": {
      "list": "roles:read",
      "create": "roles:write",
      "edit": "roles:write",
      "delete": "roles:write",
      "show": null,
      "sample": null
    }
  },
  {
    "id": "tokens",
    "label_key": "tokens.title",
    "routes": {
      "list": null,
      "create": null,
      "edit": null,
      "show": null,
      "aliases": []
    },
    "actions": {
      "list": "tokens:read",
      "create": "tokens:write",
      "edit": "tokens:write",
      "delete": "tokens:write",
      "show": null,
      "sample": null
    }
  },
  {
    "id": "sources",
    "label_key": "sources.title",
    "routes": {
      "list": "/console/sources",
      "create": null,
      "edit": null,
      "show": "/console/sources/:id/structure-diffs",
      "aliases": [
        {
          "path": "/console/sources/:id/structure-diffs/:diffId",
          "action": "show"
        }
      ]
    },
    "actions": {
      "list": "sources:read",
      "create": "sources:write",
      "edit": "sources:write",
      "delete": "sources:write",
      "show": "metadata:read",
      "sample": null
    }
  },
  {
    "id": "catalog",
    "label_key": "catalog.title",
    "routes": {
      "list": "/console/catalog",
      "create": null,
      "edit": null,
      "show": "/console/catalog/:id",
      "aliases": []
    },
    "actions": {
      "list": "metadata:read",
      "create": null,
      "edit": "metadata:write",
      "delete": null,
      "show": "metadata:read",
      "sample": "catalog:sample"
    }
  },
  {
    "id": "business-domains",
    "label_key": "businessDomains.title",
    "routes": {
      "list": "/console/business-domains",
      "create": "/console/business-domains",
      "edit": "/console/business-domains",
      "show": null,
      "aliases": []
    },
    "actions": {
      "list": "metadata:read",
      "create": "metadata:write",
      "edit": "metadata:write",
      "delete": "metadata:write",
      "show": null,
      "sample": null
    }
  },
  {
    "id": "type-mappings",
    "label_key": "typeMappings.title",
    "routes": {
      "list": "/console/type-mappings",
      "create": null,
      "edit": "/console/type-mappings",
      "show": null,
      "aliases": []
    },
    "actions": {
      "list": "metadata:read",
      "create": null,
      "edit": "metadata:write",
      "delete": null,
      "show": null,
      "sample": null
    }
  },
  {
    "id": "jobs",
    "label_key": "jobs.title",
    "routes": {
      "list": "/console/jobs",
      "create": null,
      "edit": null,
      "show": null,
      "aliases": []
    },
    "actions": {
      "list": "jobs:run",
      "create": null,
      "edit": null,
      "delete": null,
      "show": null,
      "sample": null
    }
  },
  {
    "id": "schedules",
    "label_key": "schedules.title",
    "routes": {
      "list": "/console/schedules",
      "create": null,
      "edit": "/console/schedules",
      "show": "/console/sources/:id/schedules",
      "aliases": []
    },
    "actions": {
      "list": "jobs:run",
      "create": null,
      "edit": "jobs:run",
      "delete": "jobs:run",
      "show": "jobs:run",
      "sample": null
    }
  },
  {
    "id": "settings",
    "label_key": "settings.title",
    "routes": {
      "list": "/console/settings",
      "create": null,
      "edit": null,
      "show": null,
      "aliases": []
    },
    "actions": {
      "list": "settings:read",
      "create": null,
      "edit": "settings:write",
      "delete": null,
      "show": null,
      "sample": null
    }
  },
  {
    "id": "branding",
    "label_key": "branding.title",
    "routes": {
      "list": "/console/branding",
      "create": null,
      "edit": null,
      "show": null,
      "aliases": []
    },
    "actions": {
      "list": "branding:read",
      "create": null,
      "edit": "branding:write",
      "delete": null,
      "show": null,
      "sample": null
    }
  },
  {
    "id": "model-services",
    "label_key": "modelServices.title",
    "routes": {
      "list": "/console/model-services",
      "create": "/console/model-services",
      "edit": "/console/model-services",
      "show": null,
      "aliases": []
    },
    "actions": {
      "list": "model_services:read",
      "create": "model_services:write",
      "edit": "model_services:write",
      "delete": "model_services:write",
      "show": null,
      "sample": null
    }
  },
  {
    "id": "account",
    "label_key": "account.title",
    "routes": {
      "list": null,
      "create": null,
      "edit": null,
      "show": "/console/account",
      "aliases": []
    },
    "actions": {
      "list": "console:access",
      "create": null,
      "edit": null,
      "delete": null,
      "show": "console:access",
      "sample": null
    }
  }
] as ModuleIdentity[];
