/** Generated by scripts/gen_console_module_catalog.py — do not edit. */

export const ModuleId = {
  dashboard: "dashboard",
  users: "users",
  identityProviders: "identity-providers",
  roles: "roles",
  tokens: "tokens",
  sources: "sources",
  catalog: "catalog",
  businessDomains: "business-domains",
  typeMappings: "type-mappings",
  jobs: "jobs",
  schedules: "schedules",
  settings: "settings",
  branding: "branding",
  account: "account",
} as const;

export type ModuleIdName = (typeof ModuleId)[keyof typeof ModuleId];
