"""Attribute Type to Postgres physical type, and schema-qualified identifiers."""

from __future__ import annotations

import hashlib
import re

from backend.entity.records import AttributeRecord

__all__ = [
    "ROW_ID_COLUMN",
    "ROW_ID_SQL",
    "attr_wants_index",
    "column_sql",
    "create_index_sql",
    "create_table_statements",
    "ident",
    "index_name",
    "qualified_table",
    "rename_table_statements",
    "unique_constraint_name",
]

ROW_ID_COLUMN = "row_id"
ROW_ID_SQL = f'"{ROW_ID_COLUMN}" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'

ENUMERATION_SQL = "VARCHAR(64)"

_ATTRIBUTE_TYPE_TO_PG: dict[str, str] = {
    "text": "TEXT",
    "integer": "BIGINT",
    "number": "DOUBLE PRECISION",
    "boolean": "BOOLEAN",
    "date": "DATE",
    "timestamp": "TIMESTAMPTZ",
    "time": "TIME",
    "json": "JSONB",
    "reference": "BIGINT",
    "enumeration": ENUMERATION_SQL,
}

_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_NAME_MAX = 63


def ident(name: str) -> str:
    if not _IDENT_RE.match(name):
        raise ValueError(f"invalid identifier: {name!r}")
    return f'"{name}"'


def qualified_table(schema: str, table: str) -> str:
    return f"{ident(schema)}.{ident(table)}"


def column_sql(attr: AttributeRecord, *, table: str) -> str:
    physical = _physical_type(attr)
    null_sql = " NOT NULL" if attr.required else ""
    check_sql = _enumeration_check_sql(attr, table=table)
    return f"{ident(attr.name)} {physical}{null_sql}{check_sql}"


def _physical_type(attr: AttributeRecord) -> str:
    if attr.type == "string":
        assert attr.max_length is not None
        return f"VARCHAR({attr.max_length})"
    if attr.type == "decimal":
        assert attr.precision is not None and attr.scale is not None
        return f"NUMERIC({attr.precision},{attr.scale})"
    return _ATTRIBUTE_TYPE_TO_PG[attr.type]


def _enumeration_check_sql(attr: AttributeRecord, *, table: str) -> str:
    if attr.type != "enumeration":
        return ""
    assert attr.entries
    constraint = _bounded_name("ck", table, attr.name)
    literals = ", ".join(_enum_literal(entry.code) for entry in attr.entries)
    return (
        f" CONSTRAINT {ident(constraint)} CHECK"
        f" ({ident(attr.name)} IS NULL OR {ident(attr.name)} IN ({literals}))"
    )


def _enum_literal(code: str) -> str:
    escaped = code.replace("'", "''")
    return f"'{escaped}'"


def attr_wants_index(attr: AttributeRecord) -> bool:
    return bool(attr.indexed) and not bool(attr.unique)


def unique_constraint_name(table: str, column: str) -> str:
    return _bounded_name("uq", table, column)


def index_name(table: str, column: str) -> str:
    return _bounded_name("ix", table, column)


def _bounded_name(kind: str, table: str, column: str) -> str:
    raw = f"{kind}_{table}_{column}"
    if len(raw) <= _NAME_MAX:
        return raw
    digest = hashlib.sha1(raw.encode()).hexdigest()[:8]
    prefix = f"{kind}_{digest}_"
    return prefix + column[: _NAME_MAX - len(prefix)]


def create_table_statements(
    schema: str, table: str, attributes: list[AttributeRecord]
) -> list[str]:
    parts = [ROW_ID_SQL] + [column_sql(attr, table=table) for attr in attributes]
    for attr in attributes:
        if attr.unique:
            name = unique_constraint_name(table, attr.name)
            parts.append(f"CONSTRAINT {ident(name)} UNIQUE ({ident(attr.name)})")
    statements = [f"CREATE TABLE {qualified_table(schema, table)} ({', '.join(parts)})"]
    for attr in attributes:
        if attr_wants_index(attr):
            statements.append(create_index_sql(schema, table, attr.name))
    return statements


def create_index_sql(schema: str, table: str, column: str) -> str:
    return (
        f"CREATE INDEX {ident(index_name(table, column))} "
        f"ON {qualified_table(schema, table)} ({ident(column)})"
    )


def rename_table_statements(
    schema: str,
    current: str,
    new: str,
    attributes: list[AttributeRecord],
) -> list[str]:
    statements = [
        f"ALTER TABLE {qualified_table(schema, current)} RENAME TO {ident(new)}"
    ]
    for attr in attributes:
        if attr.unique:
            statements.append(
                f"ALTER TABLE {qualified_table(schema, new)} "
                f"RENAME CONSTRAINT {ident(unique_constraint_name(current, attr.name))} "
                f"TO {ident(unique_constraint_name(new, attr.name))}"
            )
        if attr.type == "enumeration":
            statements.append(
                f"ALTER TABLE {qualified_table(schema, new)} "
                f"RENAME CONSTRAINT {ident(_bounded_name('ck', current, attr.name))} "
                f"TO {ident(_bounded_name('ck', new, attr.name))}"
            )
        if attr_wants_index(attr):
            statements.append(
                f"ALTER INDEX {ident(schema)}.{ident(index_name(current, attr.name))} "
                f"RENAME TO {ident(index_name(new, attr.name))}"
            )
    return statements
