"""Attribute Type to Postgres physical type, and schema-qualified identifiers."""

from __future__ import annotations

import hashlib
import re

from backend.entity.attribute_type import resolve
from backend.entity.records import AttributeRecord

__all__ = [
    "ACL_OWNER_ROLE",
    "ACL_SCHEMA",
    "ENTITY_ACCESS_SCHEMA",
    "ENTITY_DATA_SCHEMA",
    "ENTITY_OWNER_ROLE",
    "EXPOSURE_OWNER_ROLE",
    "EXPOSURE_POLICY",
    "OWNER_POLICY",
    "READER_ROLE",
    "ROW_ID_COLUMN",
    "ROW_ID_SQL",
    "table_security_statements",
    "attr_wants_index",
    "column_sql",
    "create_index_sql",
    "create_table_statements",
    "ident",
    "index_name",
    "comment_table_sql",
    "create_view_sql",
    "drop_view_sql",
    "qualified_table",
    "unique_constraint_name",
    "view_security_statements",
]

ROW_ID_COLUMN = "row_id"
ROW_ID_SQL = f'"{ROW_ID_COLUMN}" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'

ENTITY_DATA_SCHEMA = "entity_data"
ENTITY_ACCESS_SCHEMA = "entity_access"
ACL_SCHEMA = "acl"

ENTITY_OWNER_ROLE = "refraq_entity_owner"
EXPOSURE_OWNER_ROLE = "refraq_exposure_owner"
ACL_OWNER_ROLE = "refraq_acl_owner"
READER_ROLE = "refraq_reader"

EXPOSURE_POLICY = "refraq_exposure_read"
OWNER_POLICY = "refraq_owner_write"

_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_NAME_MAX = 63


def ident(name: str) -> str:
    if not _IDENT_RE.match(name):
        raise ValueError(f"invalid identifier: {name!r}")
    return f'"{name}"'


def qualified_table(schema: str, table: str) -> str:
    return f"{ident(schema)}.{ident(table)}"


def column_sql(attr: AttributeRecord, *, table: str) -> str:
    spec = resolve(attr.type)
    physical = spec.physical_sql(attr)
    null_sql = " NOT NULL" if attr.required else ""
    predicate = spec.check_predicate(attr, column=ident(attr.name))
    check_sql = ""
    if predicate:
        constraint = _bounded_name("ck", table, attr.name)
        check_sql = f" CONSTRAINT {ident(constraint)} CHECK ({predicate})"
    return f"{ident(attr.name)} {physical}{null_sql}{check_sql}"


def attr_wants_index(attr: AttributeRecord) -> bool:
    return bool(attr.indexed) and not bool(attr.unique)


def unique_constraint_name(table: str, column: str) -> str:
    return _bounded_name("uq", table, column)


def index_name(table: str, column: str) -> str:
    return _bounded_name("ix", table, column)


def _bounded_name(kind: str, table: str, column: str) -> str:
    raw = f"{kind}_{table}_{column}"
    if len(raw) <= _NAME_MAX:
        return raw
    digest = hashlib.sha1(raw.encode()).hexdigest()[:8]
    prefix = f"{kind}_{digest}_"
    return prefix + column[: _NAME_MAX - len(prefix)]


def create_table_statements(
    schema: str, table: str, attributes: list[AttributeRecord]
) -> list[str]:
    parts = [ROW_ID_SQL] + [column_sql(attr, table=table) for attr in attributes]
    for attr in attributes:
        if attr.unique:
            name = unique_constraint_name(table, attr.name)
            parts.append(f"CONSTRAINT {ident(name)} UNIQUE ({ident(attr.name)})")
    statements = [f"CREATE TABLE {qualified_table(schema, table)} ({', '.join(parts)})"]
    for attr in attributes:
        if attr_wants_index(attr):
            statements.append(create_index_sql(schema, table, attr.name))
    statements.extend(table_security_statements(schema, table))
    return statements


def table_security_statements(schema: str, table: str) -> list[str]:
    """RLS backstop: only the Profile View owner reads, only the owner role writes.

    Policies target roles, not ``current_user``: inside an owner-rights view the
    policy role check uses the view owner, while ``current_user`` is the invoker.
    FORCE makes the table owner subject to its own policies. The table owner is
    ``refraq_entity_owner`` even when the session that runs the DDL is not.
    """
    q = qualified_table(schema, table)
    return [
        f"ALTER TABLE {q} OWNER TO {ident(ENTITY_OWNER_ROLE)}",
        f"REVOKE ALL ON {q} FROM PUBLIC",
        f"REVOKE ALL ON {q} FROM {ident(READER_ROLE)}",
        f"ALTER TABLE {q} ENABLE ROW LEVEL SECURITY",
        f"ALTER TABLE {q} FORCE ROW LEVEL SECURITY",
        f"CREATE POLICY {ident(EXPOSURE_POLICY)} ON {q} AS PERMISSIVE "
        f"FOR SELECT TO {ident(EXPOSURE_OWNER_ROLE)} USING (true)",
        f"CREATE POLICY {ident(OWNER_POLICY)} ON {q} AS PERMISSIVE "
        f"FOR ALL TO {ident(ENTITY_OWNER_ROLE)} USING (true) WITH CHECK (true)",
        f"GRANT SELECT ON {q} TO {ident(EXPOSURE_OWNER_ROLE)}",
    ]


def view_security_statements(schema: str, view: str) -> list[str]:
    """Stem views stay owned by the entity owner and invisible to the reader."""
    q = qualified_table(schema, view)
    return [
        f"ALTER VIEW {q} OWNER TO {ident(ENTITY_OWNER_ROLE)}",
        f"REVOKE ALL ON {q} FROM PUBLIC",
        f"REVOKE ALL ON {q} FROM {ident(READER_ROLE)}",
    ]


def create_index_sql(schema: str, table: str, column: str) -> str:
    return (
        f"CREATE INDEX {ident(index_name(table, column))} "
        f"ON {qualified_table(schema, table)} ({ident(column)})"
    )


def comment_table_sql(schema: str, table: str, comment: str) -> str:
    escaped = comment.replace("'", "''")
    return f"COMMENT ON TABLE {qualified_table(schema, table)} IS '{escaped}'"


def create_view_sql(schema: str, view: str, table: str) -> str:
    return (
        f"CREATE VIEW {qualified_table(schema, view)} AS "
        f"SELECT * FROM {qualified_table(schema, table)}"
    )


def drop_view_sql(schema: str, view: str) -> str:
    return f"DROP VIEW {qualified_table(schema, view)}"
